[project]
name = "pytomator"
version = "0.1.0"
description = "Python scripted automation tool"
requires-python = ">=3.12,<3.15"
package-mode = false

dependencies = [
    "PySide6",
    "PyQt6",
    "PyQt6-QScintilla",
    "pyautogui",
    "pydirectinput",
    "keyboard",
    "mss",
    "pillow"
]
